function fig = hdrdisp()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

load hdrdisp

% modify this in the future such that if one hdrdisp figure is open, 
% it goes to that figure and initialize it.
if strcmp(get(gcf,'Tag'),'EchoFig')
   h0 = figure('Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
   'HandleVisibility','callback',...
	'Name','.EYE FILE HEADERS', ...
	'PointerShapeCData',mat1, ...
	'Position',[104 109 570 411], ...
	'Tag','HdrFig');
else
   h0 = gcf;
   set(gcf,'Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
   'HandleVisibility','callback',...
	'Name','.EYE FILE HEADERS', ...
	'PointerShapeCData',mat1, ...
	'Position',[104 109 570 411], ...
	'Tag','HdrFig');
   figure(h0)
end
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','hdrgui tmdt', ...
	'FontSize',10, ...
	'ForegroundColor',[0.5 0 0], ...
	'ListboxTop',0, ...
	'Position',[213.75 268.5 110.25 19.5], ...
	'String','Time and date', ...
	'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','hdrgui hdr', ...
	'FontSize',10, ...
	'ListboxTop',0, ...
	'Position',[8.25 273 111 15], ...
	'String',['Header version       ';'Header length (bytes)'], ...
	'Style','popupmenu', ...
	'Tag','Hdr Ppup', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','hdrgui tdr', ...
	'FontSize',10, ...
	'ForegroundColor',[0 0 1], ...
	'Position',[9 226.5 111 40.5], ...
	'String',['Transducer ID    ';'Center freq (MHz)';'Bandwidth (%)    ';'Start freq (MHz) '], ...
	'Style','listbox', ...
	'Tag','Tdr Lstbx', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ForegroundColor',[0.5 0 0], ...
	'ListboxTop',0, ...
	'Position',[327 273 45 10.5], ...
	'Style','text', ...
	'Tag','Dt Sttxt');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.9 0.9 0.9], ...
	'ForegroundColor',[0.5 0 0], ...
	'ListboxTop',0, ...
	'Position',[372.75 273 45 10.5], ...
	'Style','text', ...
	'Tag','Tm Sttxt');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[121.5 270.75 71.25 15], ...
	'Style','text', ...
	'Tag','Hdr Sttxt');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','echodisp', ...
	'FontSize',12, ...
	'FontWeight','demi', ...
	'ListboxTop',0, ...
	'Position',[90.75 19.5 106.5 20.25], ...
	'String','Display echo(es)', ...
	'Tag','Pushbutton3');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','hdrgui close', ...
	'FontSize',12, ...
	'FontWeight','demi', ...
	'ListboxTop',0, ...
	'Position',[231 20.25 84 19.5], ...
	'String','Close Figure', ...
	'Tag','Pushbutton4');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','hdrgui A2D', ...
	'FontSize',10, ...
	'ForegroundColor',[1 0 0], ...
	'Position',[8.25 178.5 111 42], ...
	'String',['Points per A-line  ';'A-lines per scan   ';'Sampling rate (MHz)';'Number of A/D bits ';'Bytes per A/D word ';'A/D type           '], ...
	'Style','listbox', ...
	'Tag','Listbox2', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','hdrgui scaninfo', ...
	'FontSize',10, ...
	'ForegroundColor',[0 0.7 0], ...
	'ListboxTop',4, ...
	'Position',[8.25 132 111 40.5], ...
	'String',['Delay (mm)         ';'pivot distance (mm)';'scan angle (deg)   ';'operator initial   ';'scan mode          ';'location           '], ...
	'Style','listbox', ...
	'Tag','Listbox3', ...
	'Value',6);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','hdrgui patinfo', ...
	'FontSize',10, ...
	'ForegroundColor',[0 0 0.3], ...
	'Position',[213.75 161.25 111 42], ...
	'String',['Patiend ID     ';'Extended ID    ';'Age            ';'Sex            ';'Scanned before?'], ...
	'Style','listbox', ...
	'Tag','Listbox2', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','hdrgui tissueinfo', ...
	'FontSize',10, ...
	'ForegroundColor',[0.3 0 0], ...
	'Position',[213.75 113.25 111 42], ...
	'String',['Organ           ';'Disease type    ';'Disease location'], ...
	'Style','listbox', ...
	'Tag','Listbox2', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','hdrgui comment', ...
	'FontSize',10, ...
	'ListboxTop',0, ...
	'Position',[9 100.5 109.5 20.25], ...
	'String','Comments', ...
	'Tag','Pushbutton5');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','hdrgui calinfo', ...
	'FontSize',10, ...
	'ForegroundColor',[0 0.3 0], ...
	'Position',[213.75 65.25 111 42], ...
	'String',['Cal. spectrum incl. in header?   ';'offset of cal. spectrum from BOF"'], ...
	'Style','listbox', ...
	'Tag','Listbox2', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','hdrgui rffile', ...
	'FontSize',10, ...
	'ForegroundColor',[0 0 0.5], ...
	'ListboxTop',0, ...
	'Position',[214.5 239.25 109.5 20.25], ...
	'String','RF file information', ...
	'Tag','Pushbutton5');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','hdrgui calfile', ...
	'FontSize',10, ...
	'ListboxTop',0, ...
	'Position',[214.5 211.5 109.5 20.25], ...
	'String','Calibratn. file information', ...
	'Tag','Pushbutton5');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',12, ...
	'ForegroundColor',[0 0 1], ...
	'ListboxTop',0, ...
	'Position',[121.5 239.25 45 15], ...
	'Style','text', ...
	'Tag','Tdr Sttxt');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',12, ...
	'ForegroundColor',[1 0 0], ...
	'ListboxTop',0, ...
	'Position',[121.5 192 45 15], ...
	'Style','text', ...
	'Tag','A/D Sttxt');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',12, ...
	'ForegroundColor',[0 0.7 0], ...
	'ListboxTop',0, ...
	'Position',[121.5 144.75 45 15], ...
	'Style','text', ...
	'Tag','ScanInfo Sttxt');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ForegroundColor',[0 0 0.5], ...
	'ListboxTop',0, ...
	'Position',[327 238.5 45 10.5], ...
	'Style','text', ...
	'Tag','RfFl Sttxt');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.9 0.9 0.9], ...
	'ForegroundColor',[0 0 0.5], ...
	'ListboxTop',0, ...
	'Position',[372.75 238.5 45 10.5], ...
	'Style','text', ...
	'Tag','RfAt Sttxt');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[327 210.75 45 10.5], ...
	'Style','text', ...
	'Tag','ClFl Sttxt');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.9 0.9 0.9], ...
	'ListboxTop',0, ...
	'Position',[372.75 210.75 45 10.5], ...
	'Style','text', ...
	'Tag','ClAt Sttxt');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',12, ...
	'ForegroundColor',[0 0 0.3], ...
	'ListboxTop',0, ...
	'Position',[327 174.75 45 15], ...
	'Style','text', ...
	'Tag','PatInfo Sttxt');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',12, ...
	'ForegroundColor',[0.3 0 0], ...
	'ListboxTop',0, ...
	'Position',[327 126.75 45 15], ...
	'Style','text', ...
	'Tag','TissueInfo Sttxt');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',12, ...
	'ForegroundColor',[0 0.3 0], ...
	'ListboxTop',0, ...
	'Position',[327 78.75 45 15], ...
	'Style','text', ...
	'Tag','CalInfo Sttxt');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',12, ...
	'ForegroundColor',[1 0 0], ...
	'ListboxTop',0, ...
	'Position',[121.5 60 81.75 60.75], ...
	'Style','text', ...
	'Tag','Comment Sttxt');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'ForegroundColor',[0 0 0.5], ...
	'ListboxTop',0, ...
	'Position',[327 249 45 10.5], ...
	'String','NAME', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'ForegroundColor',[0 0 0.5], ...
	'ListboxTop',0, ...
	'Position',[372.75 249 45 10.5], ...
	'String','Atenuation', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'ListboxTop',0, ...
	'Position',[372.75 221.25 45 10.5], ...
	'String','Atenuation', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'ListboxTop',0, ...
	'Position',[327 221.25 45 10.5], ...
	'String','NAME', ...
	'Style','text', ...
	'Tag','StaticText1');
if nargout > 0, fig = h0; end
